services:
  # Un service web Docker
  - type: web
    name: monservice
    runtime: docker
    image: monimage:latest
    ports:
      - 8080:80
    envVars:
      - key: VARIABLE1
        value: valeur1
