services:
  # Un service web Docker
  - type: web
    name: webdis
    runtime: docker
    rootDir: webdis
    dockerCommand: ./webdis.sh # facultatif (par défaut, la commande Dockerfile est utilisée)

