services:
  - name: webdis
    type: web
    runtime: docker
    rootDir: webdis
    dockerCommand: ./webdis.sh
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
      - fromGroup: conc-settings
